#!/usr/bin/env bash
set -euo pipefail

# Single SonarQube project: RediensIAM.
# Scans:
#   - ASP.NET Core API
#   - Admin SPA
#   - Login SPA

SONAR_HOST="http://192.168.1.97:9000"
ENV_FILE="$(dirname "$0")/.sonar.env"

if [[ -f "$ENV_FILE" ]]; then
    mode=$(stat -c %a "$ENV_FILE" 2>/dev/null || echo 600)
    if [[ "$mode" != "600" ]]; then
        echo "warning: $ENV_FILE had mode $mode, changing to 600"
        chmod 600 "$ENV_FILE"
    fi

    # shellcheck disable=SC1090
    source "$ENV_FILE"
fi

# Backwards compatibility with older .sonar.env
if [[ -z "${SONAR_TOKEN:-}" && -n "${SONAR_TOKEN_API:-}" ]]; then
    SONAR_TOKEN="$SONAR_TOKEN_API"
fi

if [[ -z "${SONAR_TOKEN:-}" ]]; then
    read -rsp "SonarQube token for RediensIAM: " SONAR_TOKEN
    echo

    read -rp "Save token to .sonar.env? [y/N] " save
    if [[ "$save" =~ ^[Yy]$ ]]; then
        (
            umask 077
            printf 'SONAR_TOKEN=%s\n' "$SONAR_TOKEN" >"$ENV_FILE"
        )
        chmod 600 "$ENV_FILE"
        echo "Token saved."
    fi
fi

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

echo "Using SonarQube server: $SONAR_HOST"

echo
echo "==> Scanning RediensIAM..."

rm -rf tests/RediensIAM.IntegrationTests/TestResults
rm -rf sdk/dotnet/RediensIAM.Client.Tests/TestResults
rm -rf .sonarqube
rm -rf src/bin
rm -rf src/obj

mkdir -p src/bin/Debug/net10.0

dotnet sonarscanner begin \
    /k:"RediensIAM" \
    /n:"RediensIAM" \
    /d:sonar.host.url="$SONAR_HOST" \
    /d:sonar.token="$SONAR_TOKEN" \
    /d:sonar.projectBaseDir="$ROOT" \
    `# Migrations are NOT excluded here, deliberately. They carry the <auto-generated/> header, so` \
  `# the analyser skips them on its own — while excluding the files after MSBuild had already` \
  `# analysed them left the scanner importing protobufs that referenced paths it had been told to` \
  `# forget, and warning about each one on every run.` \
  /d:sonar.exclusions="**/obj/**,**/bin/**,**/node_modules/**,**/dist/**,**/coverage/**,**/playwright-report/**,**/test-results/**,**/.sonarqube/**,**/*.min.js,**/package-lock.json" \
    `# Test code and mount points, kept out of the coverage denominator only — they stay in the` \
  `# quality analysis. tests/e2e is a Playwright suite: it is the thing that does the covering, so` \
  `# counting it as production lines to cover asks the tests to test themselves. main.tsx is the` \
  `# createRoot() call each SPA boots from, and src/test/setup.ts is the vitest harness.` \
  /d:sonar.coverage.exclusions="tests/e2e/**,**/src/main.tsx,**/src/test/setup.ts" \
    /d:sonar.cs.opencover.reportsPaths="tests/**/TestResults/**/coverage.opencover.xml,sdk/**/TestResults/**/coverage.opencover.xml" \
    /d:sonar.javascript.lcov.reportPaths="frontend/admin/coverage/lcov.info,frontend/login/coverage/lcov.info,sdk/typescript/rediensiam-web/coverage/lcov.info"

dotnet build RediensIAM.slnx --no-incremental

# The scan declares sonar.javascript.lcov.reportPaths, so the files have to exist: without them the
# scanner warns "No coverage information will be saved" and the dashboard shows the SPAs as
# untested, which is the opposite of true.
# vitest and node:test both write `SF:` paths relative to their own package, so three files end
# up called `src/api.ts` and two `src/App.tsx`. The scanner resolves those against the repo root,
# matches whichever it indexed first, and reports the other as wholly uncovered — silently, with a
# green scan. Rewriting them to repo-relative paths is what makes each record name one file.
prefix_lcov() {
  local dir="$1" file="$1/coverage/lcov.info"
  [[ -f "$file" ]] || return 0
  sed -i "s#^SF:\(\./\)\?src/#SF:${dir}/src/#" "$file"
}

for spa in admin login; do
  ( cd "${ROOT}/frontend/${spa}" && npm run test:coverage --silent ) || \
    echo "warning: coverage for frontend/${spa} failed — the scan will report none for it" >&2
  prefix_lcov "frontend/${spa}"
done

# The browser SDK runs on node:test rather than vitest, so it has its own step. It is scanned
# because the console imports it from source: a defect in it fails the console first.
( cd "${ROOT}/sdk/typescript/rediensiam-web" && mkdir -p coverage && npm run test:coverage --silent ) || \
  echo "warning: coverage for the browser SDK failed — the scan will report none for it" >&2
prefix_lcov "sdk/typescript/rediensiam-web"

dotnet test \
    tests/RediensIAM.IntegrationTests/RediensIAM.IntegrationTests.csproj \
    --collect:"XPlat Code Coverage" \
    --results-directory ./tests/RediensIAM.IntegrationTests/TestResults \
    -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover || true

# The .NET SDK has its own suite, and its own coverage: without this step the client shipped to
# integrators is scanned as production code that nothing exercises.
dotnet test \
    sdk/dotnet/RediensIAM.Client.Tests/RediensIAM.Client.Tests.csproj \
    --collect:"XPlat Code Coverage" \
    --results-directory ./sdk/dotnet/RediensIAM.Client.Tests/TestResults \
    -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover || true

dotnet sonarscanner end \
    /d:sonar.token="$SONAR_TOKEN"

echo
echo "Done."
echo "$SONAR_HOST/dashboard?id=RediensIAM"