sonar.projectKey=RediensIAM
sonar.projectName=RediensIAM
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=tests/**/TestResults/**/coverage.opencover.xml
sonar.exclusions=**/obj/**,**/bin/**,**/Migrations/**
