{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-public
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin
                port:
                  number: {{ .Values.service.admin.port }}
          - path: /internal
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin
                port:
                  number: {{ .Values.service.admin.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-public
                port:
                  number: 5000
{{- end }}
