{{- if .Values.rediensiam.ingress.public.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-public
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
spec:
  ingressClassName: {{ .Values.rediensiam.ingress.className }}
  rules:
    - host: {{ include "rediensiam.ingressPublicHost" . }}
      http:
        paths:
          - path: /api/manage
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-public
                port:
                  number: {{ .Values.rediensiam.service.public.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-public
                port:
                  number: {{ .Values.rediensiam.service.public.port }}
{{- end }}
