apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  cache-url: {{ .Values.secrets.cacheUrl | quote }}
  totp-key: {{ .Values.secrets.totpEncryptionKey | quote }}
  argon2-pepper: {{ .Values.secrets.argon2Pepper | quote }}
