apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database-url:      {{ .Values.rediensiam.secrets.databaseUrl | quote }}
  cache-url:         {{ .Values.rediensiam.secrets.cacheUrl | quote }}
  totp-key:          {{ .Values.rediensiam.secrets.encryptionKey | quote }}
  smtp-password:     {{ .Values.rediensiam.secrets.smtpPassword | quote }}
  bootstrap-email:   {{ .Values.rediensiam.secrets.bootstrapEmail | default "" | quote }}
  bootstrap-password: {{ .Values.rediensiam.secrets.bootstrapPassword | default "" | quote }}
  postgres-password: {{ .Values.rediensiam.postgres.local.password | quote }}
  dragonfly-password: {{ .Values.rediensiam.dragonfly.local.password | quote }}
