apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-public
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: public
      port: {{ .Values.rediensiam.service.public.port }}
      targetPort: {{ .Values.rediensiam.service.public.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: admin
      port: {{ .Values.rediensiam.service.admin.port }}
      targetPort: {{ .Values.rediensiam.service.admin.port }}
      nodePort: {{ .Values.rediensiam.service.admin.nodePort }}
